# Importing libraries

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

ImportError: DLL load failed while importing _arpack: The specified procedure could not be found.

# importing dataset

In [8]:
car_df=pd.read_csv(r'C:\Users\user\Desktop\SAPNA\CAR_AMOUNT_PREDICTION\Predict-Car-Purchasing-Amount-using-ANN-master\Car_Purchasing_Data.csv',encoding = 'ISO-8859-1')

In [9]:
car_df

Customer Name                                    Customer e-mail  \
0      Martina Avila  cubilia.Curae.Phasellus@quisaccumsanconvallis.edu   
1      Harlan Barnes                                eu.dolor@diam.co.uk   
2    Naomi Rodriquez  vulputate.mauris.sagittis@ametconsectetueradip...   
3    Jade Cunningham                            malesuada@dignissim.com   
4       Cedric Leach     felis.ullamcorper.viverra@egetmollislectus.net   
..               ...                                                ...   
495           Walter                                ligula@Cumsociis.ca   
496            Vanna                 Cum.sociis.natoque@Sedmolestie.edu   
497            Pearl                      penatibus.et@massanonante.com   
498             Nell                  Quisque.varius@arcuVivamussit.net   
499            Marla                          Camaron.marla@hotmail.com   

          Country  Gender        Age  Annual Salary  Credit Card Debt  \
0        Bulgaria       0  41.851720    62812.09301      11609.380910   
1          Belize       0  40.870623    66646.89292       9572.957136   
2         Algeria       1  43.152897    53798.55112      11160.355060   
3    Cook Islands       1  58.271369    79370.03798      14426.164850   
4          Brazil       1  57.313749    59729.15130       5358.712177   
..            ...     ...        ...            ...               ...   
495         Nepal       0  41.462515    71942.40291       6995.902524   
496      Zimbabwe       1  37.642000    56039.49793      12301.456790   
497   Philippines       1  53.943497    68888.77805      10611.606860   
498      Botswana       1  59.160509    49811.99062      14013.034510   
499        marlal       1  46.731152    61370.67766       9391.341628   

       Net Worth  Car Purchase Amount  
0    238961.2505          35321.45877  
1    530973.9078          45115.52566  
2    638467.1773          42925.70921  
3    548599.0524          67422.36313  
4    560304.0671          55915.46248  
..           ...                  ...  
495  541670.1016          48901.44342  
496  360419.0988          31491.41457  
497  764531.3203          64147.28888  
498  337826.6382          45442.15353  
499  462946.4924          45107.22566  

[500 rows x 9 columns]

In [10]:
car_df.head(5)

Customer Name                                    Customer e-mail  \
0    Martina Avila  cubilia.Curae.Phasellus@quisaccumsanconvallis.edu   
1    Harlan Barnes                                eu.dolor@diam.co.uk   
2  Naomi Rodriquez  vulputate.mauris.sagittis@ametconsectetueradip...   
3  Jade Cunningham                            malesuada@dignissim.com   
4     Cedric Leach     felis.ullamcorper.viverra@egetmollislectus.net   

        Country  Gender        Age  Annual Salary  Credit Card Debt  \
0      Bulgaria       0  41.851720    62812.09301      11609.380910   
1        Belize       0  40.870623    66646.89292       9572.957136   
2       Algeria       1  43.152897    53798.55112      11160.355060   
3  Cook Islands       1  58.271369    79370.03798      14426.164850   
4        Brazil       1  57.313749    59729.15130       5358.712177   

     Net Worth  Car Purchase Amount  
0  238961.2505          35321.45877  
1  530973.9078          45115.52566  
2  638467.1773          42925.70921  
3  548599.0524          67422.36313  
4  560304.0671          55915.46248

In [11]:
car_df.tail(10)

Customer Name                          Customer e-mail  \
490         Jonah                  augue@risusNuncac.co.uk   
491       Merrill                   dolor.sit@turpisIn.com   
492         Nolan                 Donec.at@neccursus.co.uk   
493        Winter    egestas.urna.justo@maurissagittis.edu   
494         Rigel  egestas.blandit.Nam@semvitaealiquam.com   
495        Walter                      ligula@Cumsociis.ca   
496         Vanna       Cum.sociis.natoque@Sedmolestie.edu   
497         Pearl            penatibus.et@massanonante.com   
498          Nell        Quisque.varius@arcuVivamussit.net   
499         Marla                Camaron.marla@hotmail.com   

                   Country  Gender        Age  Annual Salary  \
490                Myanmar       1  45.752698    63722.00164   
491                  Egypt       1  50.197205    78518.21527   
492                 Latvia       0  55.087720    72424.80112   
493      Wallis and Futuna       0  42.900187    77665.17195   
494  Sao Tome and Principe       0  51.767418    77345.61633   
495                  Nepal       0  41.462515    71942.40291   
496               Zimbabwe       1  37.642000    56039.49793   
497            Philippines       1  53.943497    68888.77805   
498               Botswana       1  59.160509    49811.99062   
499                 marlal       1  46.731152    61370.67766   

     Credit Card Debt    Net Worth  Car Purchase Amount  
490      10711.444720  316128.4002          41352.47071  
491      10072.482980  294506.0844          52785.16947  
492       9831.184792  523680.7699          60117.67886  
493      13308.879320  349588.5608          47760.66427  
494       6736.751680  665099.1390          64188.26862  
495       6995.902524  541670.1016          48901.44342  
496      12301.456790  360419.0988          31491.41457  
497      10611.606860  764531.3203          64147.28888  
498      14013.034510  337826.6382          45442.15353  
499       9391.341628  462946.4924          45107.22566

# visualize dataset

In [13]:
sns.pairplot(car_df)

NameError: name 'sns' is not defined

# CREATE TESTING AND TRAINING DATASET/DATA CLEANING

In [3]:
x=car_df.drop(['Customer Name','Customer e-mail','Country','Car Purchase Amount'],axis=1)

NameError: name 'car_df' is not defined

In [4]:
x

NameError: name 'x' is not defined

In [68]:
y=car_df['Car Purchase Amount']

In [69]:
y

0      35321.45877
1      45115.52566
2      42925.70921
3      67422.36313
4      55915.46248
          ...     
495    48901.44342
496    31491.41457
497    64147.28888
498    45442.15353
499    45107.22566
Name: Car Purchase Amount, Length: 500, dtype: float64

In [70]:
x.shape

(500, 5)

In [72]:
y.shape

(500,)

In [75]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
x_scaled=scaler.fit_transform(x)

In [76]:
x_scaled

array([[0.        , 0.4370344 , 0.53515116, 0.57836085, 0.22342985],
       [0.        , 0.41741247, 0.58308616, 0.476028  , 0.52140195],
       [1.        , 0.46305795, 0.42248189, 0.55579674, 0.63108896],
       ...,
       [1.        , 0.67886994, 0.61110973, 0.52822145, 0.75972584],
       [1.        , 0.78321017, 0.37264988, 0.69914746, 0.3243129 ],
       [1.        , 0.53462305, 0.51713347, 0.46690159, 0.45198622]])

In [77]:
x_scaled.shape

(500, 5)

In [78]:
scaler.data_max_

array([1.e+00, 7.e+01, 1.e+05, 2.e+04, 1.e+06])

In [79]:
scaler.data_min_

array([    0.,    20., 20000.,   100., 20000.])

In [82]:
y=y.values.reshape(-1,1)

In [83]:
y_scaled=scaler.fit_transform(y)

In [84]:
y_scaled

array([[0.37072477],
       [0.50866938],
       [0.47782689],
       [0.82285018],
       [0.66078116],
       [0.67059152],
       [0.28064374],
       [0.54133778],
       [0.54948752],
       [0.4111198 ],
       [0.70486638],
       [0.46885649],
       [0.27746526],
       [0.56702642],
       [0.57056385],
       [0.61996151],
       [0.46217916],
       [0.49157341],
       [0.50188722],
       [0.64545808],
       [0.59339372],
       [0.48453965],
       [0.53860366],
       [0.53007738],
       [0.50814651],
       [0.49841668],
       [0.3966416 ],
       [0.56467566],
       [0.6950749 ],
       [0.49287831],
       [0.12090943],
       [0.50211776],
       [0.80794216],
       [0.62661214],
       [0.43394857],
       [0.60017103],
       [0.42223485],
       [0.01538345],
       [0.37927499],
       [0.64539707],
       [0.51838974],
       [0.45869677],
       [0.26804521],
       [0.2650104 ],
       [0.84054134],
       [0.84401542],
       [0.35515157],
       [0.406

# training the model

In [91]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test =train_test_split(x_scaled,y_scaled,test_size=0.15)

In [92]:
x_train.shape

(425, 5)

In [93]:
x_test.shape

(75, 5)

# Create a virtual environment - conda create -n tensorflow
Go inside your virtual environment - (on macOS/Linux:) source activate tensorflow (on Windows: activate tensorflow)
Inside that install tensorflow. You can install it using pip
Finish install
If you are not inside the virtual environment type - Source Activate  Tensorflow
Then inside this again install your Jupiter notebook and Pandas libraries, because there can be some missing in this virtual environment
Inside the virtual environment just type:

pip install jupyter notebook
pip install pandas
Then you can launch jupyter notebook saying:

jupyter notebook
Select the correct terminal python 3 or 2
Then import those modules

In [95]:
import tensorflow.keras

ModuleNotFoundError: No module named 'tensorflow'